# Generated by Django 5.0 on 2024-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='whatsapp_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
